// WARNING: This file is automatically generated. Any changes will be lost the next time the generator is run.

import {default as all} from './all'
import {default as base} from './base'
import {default as jest} from './jest'
import {default as json} from './json'
import {default as recommended} from './recommended'
import {default as sorting} from './sorting'
import {default as typescript} from './typescript'
import {default as unicorn} from './unicorn'
import {default as vue} from './vue'
import {default as yaml} from './yaml'

export {default as all} from './all'
export {default as base} from './base'
export {default as jest} from './jest'
export {default as json} from './json'
export {default as recommended} from './recommended'
export {default as sorting} from './sorting'
export {default as typescript} from './typescript'
export {default as unicorn} from './unicorn'
export {default as vue} from './vue'
export {default as yaml} from './yaml'

export default { all, base, jest, json, recommended, sorting, typescript, unicorn, vue, yaml }
