// WARNING: This file is automatically generated. Any changes will be lost the next time the generator is run.

import {default as eslint} from './eslint'
import {default as jest} from './jest'
import {default as json} from './json'
import {default as sorting} from './sorting'
import {default as typescript} from './typescript'
import {default as unicorn} from './unicorn'
import {default as vue} from './vue'
import {default as yaml} from './yaml'

export * as eslint from './eslint'
export * as jest from './jest'
export * as json from './json'
export * as sorting from './sorting'
export * as typescript from './typescript'
export * as unicorn from './unicorn'
export * as vue from './vue'
export * as yaml from './yaml'

export default { eslint, jest, json, sorting, typescript, unicorn, vue, yaml }
