name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build, lint, and Test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: remedyred/check-action@v1.2.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
